// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const isProduction = process.env.STAGE === 'prod';
const seedCommand = isProduction
  ? 'node dist/prisma/seed.js'
  : 'ts-node prisma/seed.ts';

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: seedCommand,
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
